In [1]:
import numpy as np


In [2]:
data=np.random.rand(10)
print(data)

[0.20020852 0.52440145 0.76174296 0.72432725 0.96271127 0.95774965
 0.7378201  0.89674783 0.82838865 0.88378716]


In [6]:
data1=[1,2,3,4,5]
arr1=np.array(data1)
print(data1)
print(arr1)
print(type(data1))
print(type(arr1))
print(arr1.shape)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
(5,)


In [8]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [13]:
x=np.random.rand(5)
y=np.random.rand(5)
z=np.maximum(x,y)
print(x);print(y);print(z)

[0.75904075 0.88290761 0.21617472 0.94330205 0.60376613]
[0.44320951 0.5743047  0.62589377 0.32467749 0.34043583]
[0.75904075 0.88290761 0.62589377 0.94330205 0.60376613]


In [15]:
z=[]
z2=[]
for i in range(0,5,1):
    if(x[i]>y[i]):
        z.append(x[i])
    else:
        z.append(y[i])
print(z)

[0.7590407535761763, 0.8829076121835452, 0.6258937727434256, 0.9433020511073937, 0.603766130819495]


In [29]:
data=[[5,2,3],[5,1,6],[7,3,9]]
arr1=np.array(data)
print(arr1)

[[5 2 3]
 [5 1 6]
 [7 3 9]]


In [31]:
print(arr1.sum())
print(arr1.mean())
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))
print(np.sort(arr1,axis=0))

41
4.555555555555555
[17  6 18]
[10 12 19]
[[5 1 3]
 [5 2 6]
 [7 3 9]]


In [34]:
data=[1,2,1,3,2]
arr1=np.array(data)
print(arr1)

[1 2 1 3 2]


In [36]:
print(np.unique(arr1))#중복값 제거

[1 2 3]
