In [9]:
import numpy as np


In [16]:
data=np.loadtxt("data/ratings1.csv",delimiter=",",dtype=np.float64)
print(data[:5,:])
print(data.shape)

[[1.00000000e+00 1.00000000e+00 4.00000000e+00 9.64982703e+08]
 [1.00000000e+00 3.00000000e+00 4.00000000e+00 9.64981247e+08]
 [1.00000000e+00 6.00000000e+00 4.00000000e+00 9.64982224e+08]
 [1.00000000e+00 4.70000000e+01 5.00000000e+00 9.64983815e+08]
 [1.00000000e+00 5.00000000e+01 5.00000000e+00 9.64982931e+08]]
(100836, 4)


In [23]:
mean_rating=data[:,2].mean()
print(mean_rating)

3.501556983616962


In [48]:
movie_ids=np.unique(data[:,1])
print(movie_ids)
print(len(movie_ids))

[1.00000e+00 2.00000e+00 3.00000e+00 ... 1.93585e+05 1.93587e+05
 1.93609e+05]
9724


In [29]:
user_ids=np.unique(data[:,0])

In [35]:
mean_values=[]
for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id,:]
    value=data_for_user[:,2].mean()
    mean_values.append([user_id,value])
mean_values[:5]

[[1.0, 4.366379310344827],
 [2.0, 3.9482758620689653],
 [3.0, 2.4358974358974357],
 [4.0, 3.5555555555555554],
 [5.0, 3.6363636363636362]]

In [50]:
mean_values=[] #for(String :list)
for movie_id in movie_ids:
    data_for_movie=data[data[:,1]==movie_id,:]
    value=data_for_movie[:,2].mean()
    mean_values.append([movie_id,value])
mean_values[:5]

[[1.0, 3.9209302325581397],
 [2.0, 3.4318181818181817],
 [3.0, 3.2596153846153846],
 [4.0, 2.357142857142857],
 [5.0, 3.0714285714285716]]

In [25]:
user_id=np.unique(data[:,0])
print(user_id)
print(len(user_id))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168.
 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182.
 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196.
 197. 